### ISSUE TITLE
Update zend-hydrator

### ISSUE THREAD

**Issue by aleksandr-yulin** [doctrine/doctrine-zend-hydrator#6]
Update to ^3.0 version

**Comment by michalbundyra** [comment]
@aleksandr-yulin It is already done on dev-develop, we are waiting for Laminas to be launched (should happen in November 2019) and then we have it released.

I would appreciate if you can test dev-develop branch and confirm it works as you expect.

Thanks!

**Comment by aleksandr-yulin** [comment]
I don’t promise (because I can’t check it on the production and can't switch to dev-develop on any version) but I will try to test it.

Thank you for still supporting this library!

**Comment by michalbundyra** [comment]
Please see https://github.com/doctrine/doctrine-laminas-hydrator

This library probably should be marked as abandoned now.
