### ISSUE TITLE
Usage Question - Hydration of objects with constructors

### ISSUE THREAD

**Issue by Saeven** [doctrine/doctrine-zend-hydrator#7]
Hello!

Does this only work in cases where the constructors aren't defined for your objects?  For example, if looking at your README, your BlogPost entity required a string title: how would you wire it?

```
class BlogPost {
    public function __construct( string $title ){
        $this->title = $title;
    }
}
```

You wouldn't be able to do this here:

```
        $this->setHydrator(new DoctrineHydrator($objectManager))
             ->setObject(new BlogPost());
```

And using 'fake' values breaks domain design.  

How would you go about things?

Thanks!

**Comment by TomHAnderson** [comment]
You could try https://github.com/Ocramius/Instantiator
